### ISSUE TITLE
How to setup PATH environment variable for vagrant on Mac OS X

### ISSUE THREAD

**Issue by naumanahmed19** [bbenoist/vscode-vagrant#3]
Hi can you please guide me how to setup PATH environment variable for vagrant.

**Comment by bbenoist** [comment]
Hi, on which OS are you?

If you used the installer on Windows, you might need to log out and log back:

> The installer will automatically add vagrant to your system path so that it is available in terminals. If it is not found, please try logging out and logging back in to your system (this is particularly necessary sometimes for Windows).

**Comment by naumanahmed19** [comment]
I am on OS X (mac).

**Comment by bbenoist** [comment]
As I understood it, Vagrant does not installs itself in the PATH on Mac as it is installed in `/usr/local` (see https://github.com/mitchellh/vagrant-installers/issues/54). Which means that the `vagrant` executable should be located at `/usr/local/bin/vagrant`.

You need to add `/usr/local/bin` in your `PATH` environment variable.

To do so, you can use the method described [here](http://superuser.com/questions/324616). This [more detailed document](http://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/) could also be helpful.

Once done, you should be able to use `vagrant` commands from your terminal (that's what the extension uses).

> **Note:** As with any environment variable change, you might need to reload your OS in-order to get the variable readable by every process.
