### ISSUE TITLE
Console output empty

### ISSUE THREAD

**Issue by rvanlieshout** [bbenoist/vscode-vagrant#4]
Thank you for your addition to Visual Studio Code. It makes life a bit better :) The only 'issue' I have is that my console output remains empty even when commands have been executed successfully.

Is there a way I can provide debugging info for you?

**Comment by JoBrad** [comment]
I know this is an old issue, but since there aren't any comments my experience may help. I was able to find error logs for this extension by switching to the "Log (Window)" channel in the Output panel.
