### ISSUE TITLE
VSCODE Version 1.9.1 on vagrant 1.9.1 Not working 

### ISSUE THREAD

**Issue by jamroks** [bbenoist/vscode-vagrant#5]
HI,

 thanks a lot for your plugin, i'm new to vscode and just installed vscode Version 1.9.1, and the plugin does'nt seem to work at all . i mean there is no output ! when i have a running vagrant vm launched via the mac os terminal, then i switched to vscode and issue a "> vagrant: status " nothing seems to happen nothing shows in output view. 
is the plugin still compatible with vscode 1.9.1

**Comment by mradcliffe** [comment]
I have the exact same experience trying to use the extension running vagrant 1.8.7. Typed "> vagrant: status", nothing happens. Opened "> vagant: Show log", console opens up, it's blank.

**Comment by bbenoist** [comment]
Thanks for the feedback! Sorry for the late reply, I had to concentrate on the first weeks of my new dream job 😉 

Issue should have been fixed with latest version of the extension.

Please let me know if the fix is effective on your side too.
I'll reopen this issue if it's not.
